name: Java with IzPack Snapshot Setup

on: [push]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Install Required Packages
        run: sudo apt install gettext
      - name: Checkout Main Repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '3.9.9'
      - name: Clone IzPack Repository
        uses: actions/checkout@v4
        with:
          repository: 'izpack/izpack'
          path: 'izpack-source'
      - name: Build IzPack Snapshot
        working-directory: ./izpack-source
        run: |
          mvn clean install -DskipTests
          ls $GITHUB_WORKSPACE/izpack-source/izpack-dist/target/IzPack
          echo "IZPACK_HOME=$GITHUB_WORKSPACE/izpack-source/izpack-dist/target/IzPack" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/izpack-source/izpack-dist/target/IzPack/bin" >> $GITHUB_PATH
      - name: Generate Properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "izpack.home=${{ env.IZPACK_HOME }}" >> override.properties
      - name: Verify Setup
        run: |
          java -version
          ant -version
          echo "IzPack installation directory: $IZPACK_HOME"
          ls -l $IZPACK_HOME/bin
      - name: Upload IzPack Build
        uses: actions/upload-artifact@v4
        with:
          name: izpack-snapshot-${{ github.sha }}
          path: ${{ env.IZPACK_HOME }}
          retention-days: 1
      - name: Cache IzPack Build
        uses: actions/cache@v3
        with:
          path: izpack-source
          key: izpack-snapshot-${{ github.sha }}
          restore-keys: |
            izpack-snapshot-
      #- name: Build I2P installer
